-- Grupos de amostras por demanda.
-- Migration aditiva para alinhar o banco local ao fluxo atual de Orçamentos.

create table if not exists demanda_grupos_amostras (
  id bigint generated by default as identity primary key,
  demanda_id bigint not null references demandas_propostas(id) on delete cascade,
  identificacao text not null,
  tipo_matriz text,
  quantidade_amostras integer not null default 1 check (quantidade_amostras > 0),
  unidade text not null default 'amostras',
  observacao text,
  ordem integer not null default 1,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table demanda_analises
  add column if not exists grupo_amostra_id bigint references demanda_grupos_amostras(id) on delete set null;

create index if not exists demanda_grupos_amostras_demanda_id_idx
  on demanda_grupos_amostras(demanda_id);

create index if not exists demanda_analises_grupo_amostra_id_idx
  on demanda_analises(grupo_amostra_id);
