-- =====================================================================
-- Reconciliacao de privilegios historicos de Governanca.
--
-- O baseline b75d83c tinha cinco papeis:
-- usuario, coordenador, administrativo, gerente, administrador.
-- O modelo atual de perfis/RLS aceita quatro papeis:
-- tecnico, coordenador, gestor, admin.
--
-- Esta migration nao recria o papel administrativo nem altera checks de
-- perfis. Ela recupera as capacidades granulares historicas dentro da
-- tabela editavel permissoes_categorias, preservando valores ja alterados.
-- =====================================================================

insert into permissoes_categorias (papel, permissoes)
values
  ('tecnico', '{
    "analises.ver": true,
    "analises.editar": false,
    "insumos.ver": true,
    "insumos.editar": false,
    "custeio.ver": true,
    "estoque.ver": true,
    "estoque.movimentar": true,
    "estoque.descartar_bloquear": false,
    "estoque.lote.aceitar": false,
    "estoque.lote.gerir": false,
    "planejamento.ver": true,
    "planejamento.editar": false,
    "pedido.ver": true,
    "pedido.criar": true,
    "pedido.aprovar": false,
    "compras.ver": true,
    "compras.solicitar": true,
    "compras.aprovar": false,
    "compras.receber": false,
    "compras.cancelar": false,
    "recebimento.ver": true,
    "recebimento.registrar": false,
    "orcamentos.visualizar": true,
    "orcamentos.criar_editar": true,
    "orcamentos.emitir": false,
    "orcamentos.cancelar": false,
    "orcamento.parametros.editar": false,
    "projetos.ver": true,
    "projetos.editar": false,
    "cadastros.ver": true,
    "cadastros.editar": false,
    "auditoria.visualizar": false,
    "usuarios.gerenciar": false,
    "backups.gerenciar": false,
    "privilegios.gerenciar": false,
    "configuracoes.ver": false
  }'::jsonb),
  ('coordenador', '{
    "analises.ver": true,
    "analises.editar": true,
    "insumos.ver": true,
    "insumos.editar": true,
    "custeio.ver": true,
    "estoque.ver": true,
    "estoque.movimentar": true,
    "estoque.descartar_bloquear": false,
    "estoque.lote.aceitar": true,
    "estoque.lote.gerir": false,
    "planejamento.ver": true,
    "planejamento.editar": true,
    "pedido.ver": true,
    "pedido.criar": true,
    "pedido.aprovar": true,
    "compras.ver": true,
    "compras.solicitar": true,
    "compras.aprovar": true,
    "compras.receber": true,
    "compras.cancelar": false,
    "recebimento.ver": true,
    "recebimento.registrar": true,
    "orcamentos.visualizar": true,
    "orcamentos.criar_editar": true,
    "orcamentos.emitir": true,
    "orcamentos.cancelar": false,
    "orcamento.parametros.editar": false,
    "projetos.ver": true,
    "projetos.editar": true,
    "cadastros.ver": true,
    "cadastros.editar": true,
    "auditoria.visualizar": false,
    "usuarios.gerenciar": false,
    "backups.gerenciar": false,
    "privilegios.gerenciar": false,
    "configuracoes.ver": false
  }'::jsonb),
  ('gestor', '{
    "analises.ver": true,
    "analises.editar": true,
    "insumos.ver": true,
    "insumos.editar": true,
    "custeio.ver": true,
    "estoque.ver": true,
    "estoque.movimentar": true,
    "estoque.descartar_bloquear": true,
    "estoque.lote.aceitar": true,
    "estoque.lote.gerir": true,
    "planejamento.ver": true,
    "planejamento.editar": true,
    "pedido.ver": true,
    "pedido.criar": true,
    "pedido.aprovar": true,
    "compras.ver": true,
    "compras.solicitar": true,
    "compras.aprovar": true,
    "compras.receber": true,
    "compras.cancelar": true,
    "recebimento.ver": true,
    "recebimento.registrar": true,
    "orcamentos.visualizar": true,
    "orcamentos.criar_editar": true,
    "orcamentos.emitir": true,
    "orcamentos.cancelar": true,
    "orcamento.parametros.editar": true,
    "projetos.ver": true,
    "projetos.editar": true,
    "cadastros.ver": true,
    "cadastros.editar": true,
    "auditoria.visualizar": true,
    "usuarios.gerenciar": false,
    "backups.gerenciar": false,
    "privilegios.gerenciar": false,
    "configuracoes.ver": true
  }'::jsonb),
  ('admin', '{
    "analises.ver": true,
    "analises.editar": true,
    "insumos.ver": true,
    "insumos.editar": true,
    "custeio.ver": true,
    "estoque.ver": true,
    "estoque.movimentar": true,
    "estoque.descartar_bloquear": true,
    "estoque.lote.aceitar": true,
    "estoque.lote.gerir": true,
    "planejamento.ver": true,
    "planejamento.editar": true,
    "pedido.ver": true,
    "pedido.criar": true,
    "pedido.aprovar": true,
    "compras.ver": true,
    "compras.solicitar": true,
    "compras.aprovar": true,
    "compras.receber": true,
    "compras.cancelar": true,
    "recebimento.ver": true,
    "recebimento.registrar": true,
    "orcamentos.visualizar": true,
    "orcamentos.criar_editar": true,
    "orcamentos.emitir": true,
    "orcamentos.cancelar": true,
    "orcamento.parametros.editar": true,
    "projetos.ver": true,
    "projetos.editar": true,
    "cadastros.ver": true,
    "cadastros.editar": true,
    "auditoria.visualizar": true,
    "usuarios.gerenciar": true,
    "backups.gerenciar": true,
    "privilegios.gerenciar": true,
    "configuracoes.ver": true
  }'::jsonb)
on conflict (papel) do update
set permissoes = excluded.permissoes || permissoes_categorias.permissoes,
    atualizado_em = now();
